const modelNameMap = {
  information_retrieval: 'information_retrieval',
  federated_training: 'federated_training',
  feature_engineering: 'feature_engineering',
  sample_intersection: 'sample_intersection',
  homoLR: 'HomoLR',
  heteroLR: 'HeteroLR',
  heteroLinR: 'HeteroLinR',
  sklearnLR: 'LocalBaseline',
  dataIO: 'DataIO',
  evaluation: 'Evaluation',
  boost: 'HeteroSecureBoost',
  binning: 'HeteroFeatureBinning',
  homoBinning: 'HomoFeatureBinning',
  selection: 'HeteroFeatureSelection',
  scale: 'FeatureScale',
  sample: 'FederatedSample',
  oneHot: 'OneHotEncoder',
  poisson: 'HeteroPoisson',
  homoNN: 'HomoNN',
  heteroNN: 'HeteroNN',
  correlation: 'HeteroPearson',
  homoBoost: 'HomoSecureboost',
  heterofm: 'HeteroFM',
  homofm: 'HomoFM',
  heteroMF: 'HeteroMF',
  heteroSVD: 'HeteroSVD',
  heteroSVDPP: 'HeteroSVDPP',
  heteroGMF: 'HeteroGMF',
  psi: 'PSI',
  statistic: 'DataStatistics',
  reader: 'Reader',
  scorecard: 'Scorecard',
  transformer: 'Transformer',
};

export default modelNameMap;
