export default {
  //样本采样 随机采样参数
  sample_random: [
    {
      default: 'random',
      desc: 'sample algorithm and parameters',
      name: 'sample_algorithm',
      options: ['random', 'system', 'stratify'],
      renderType: 'select',
      type: 'AT_UNION_GROUP',
      hidden: false,
    },
    {
      default: 0.8,
      desc: 'Proportion of the dataset to sample in the set. The fraction should be larger than 0.',
      name: 'frac',
      renderType: 'input',
      type: 'AT_FLOAT',
      hidden: false,
    },
    {
      default: 1024,
      desc: 'Specify the random seed of the shuffling.',
      name: 'random_state',
      renderType: 'input',
      type: 'AT_INT',
      hidden: false,
    },
    {
      default: false,
      desc: 'If true, sampling with replacement. If false, sampling without replacement.',
      name: 'replacement',
      options: [true, false],
      renderType: 'select',
      type: 'AT_BOOL',
      hidden: false,
    },
  ],
  //样本采样  等距采样参数
  sample_system: [
    {
      default: 'system',
      desc: 'sample algorithm and parameters',
      name: 'sample_algorithm',
      options: ['random', 'system', 'stratify'],
      renderType: 'select',
      type: 'AT_UNION_GROUP',
      hidden: false,
    },
    {
      default: 0.2,
      desc: 'Proportion of the dataset to sample in the set. The fraction should be larger than 0.',
      name: 'frac',
      renderType: 'input',
      type: 'AT_FLOAT',
      hidden: false,
    },
  ],
  //样本采样 分层采样参数
  sample_stratify: [
    {
      default: 'stratify',
      desc: 'sample algorithm and parameters',
      name: 'sample_algorithm',
      options: ['random', 'system', 'stratify'],
      renderType: 'select',
      type: 'AT_UNION_GROUP',
      hidden: false,
    },
    {
      default: 0.8,
      desc: 'Proportion of the dataset to sample in the set. The fraction should be larger than 0.',
      name: 'frac',
      renderType: 'input',
      type: 'AT_FLOAT',
      hidden: false,
    },
    {
      default: '',
      desc: 'stratify sample observe feature.',
      name: 'observe_feature',
      renderType: 'input',
      type: 'AT_STRING',
      hidden: false,
    },
    {
      default: '',
      desc: 'stratify sample quantiles',
      name: 'quantiles',
      renderType: 'input',
      type: 'AT_FLOATS',
      hidden: false,
    },
    {
      default: '',
      desc: 'If true, sampling with replacement. If false, sampling without replacement.',
      name: 'replacements',
      options: [true, false],
      renderType: 'select',
      type: 'AT_BOOLS',
      hidden: false,
    },
    {
      default: 1024,
      desc: 'Specify the random seed of the shuffling.',
      name: 'random_state',
      renderType: 'input',
      type: 'AT_INT',
      hidden: false,
    },
    {
      default: '',
      desc: 'stratify sample weights',
      name: 'weights',
      renderType: 'input',
      type: 'AT_FLOATS',
      hidden: true,
    },
  ],
};
